services:
  nginx:
    image: nginx:latest
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/apps:/etc/nginx/conf.d/apps:ro
      - ./nginx/utils:/etc/nginx/conf.d/utils:ro
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - web
      - agent
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PUBLIC_URL=http://localhost
    volumes:
      - type: bind
        source: ./agent
        target: /app
      - type: bind
        source: ./modules
        target: /modules
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_PUBLIC_API_URL=http://localhost
    volumes:
      - type: bind
        source: ./web
        target: /app
